// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkP6VweCzMZd97Ml3SqHTX5AppxkXdSH4',
    appId: '1:557291980887:web:06ec892fa7dd51ddbd3b12',
    messagingSenderId: '557291980887',
    projectId: 'safar_kar-46bbb',
    authDomain: 'safar_kar-46bbb.firebaseapp.com',
    storageBucket: 'safar_kar-46bbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKaIdKT9fT1lMAWpViM3UIJFX3y6-8auE',
    appId: '1:557291980887:android:ff3fdc20b899ce38bd3b12',
    messagingSenderId: '557291980887',
    projectId: 'safar_kar-46bbb',
    storageBucket: 'safar_kar-46bbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8vl1LdfGdbJhJkIfZe6PWaYBglGqHWGA',
    appId: '1:557291980887:ios:0bb315d8ed29970bbd3b12',
    messagingSenderId: '557291980887',
    projectId: 'safar_kar-46bbb',
    storageBucket: 'safar_kar-46bbb.appspot.com',
    iosBundleId: 'com.example.safar_kar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8vl1LdfGdbJhJkIfZe6PWaYBglGqHWGA',
    appId: '1:557291980887:ios:c30f8e4804e79c46bd3b12',
    messagingSenderId: '557291980887',
    projectId: 'safar_kar-46bbb',
    storageBucket: 'safar_kar-46bbb.appspot.com',
    iosBundleId: 'com.example.safar_kar.RunnerTests',
  );
}
