// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUcuJUlZ58c1Cicxse5jGD_6F2_aB4-LU',
    appId: '1:747545349252:web:57482f5867f787073706d1',
    messagingSenderId: '747545349252',
    projectId: 'wallet-89599',
    authDomain: 'wallet-89599.firebaseapp.com',
    storageBucket: 'wallet-89599.appspot.com',
    measurementId: 'G-L1HMFC1KMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIH1vuFo4NeRMDsLFFAbOSsQ20coA5Gwk',
    appId: '1:747545349252:android:2d5165f12f85f5813706d1',
    messagingSenderId: '747545349252',
    projectId: 'wallet-89599',
    storageBucket: 'wallet-89599.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPVJnq9gJEXGkOVB-7s1HEyFKv97HkTvI',
    appId: '1:747545349252:ios:71a009b2fe19f0973706d1',
    messagingSenderId: '747545349252',
    projectId: 'wallet-89599',
    storageBucket: 'wallet-89599.appspot.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPVJnq9gJEXGkOVB-7s1HEyFKv97HkTvI',
    appId: '1:747545349252:ios:d92f186c859d87063706d1',
    messagingSenderId: '747545349252',
    projectId: 'wallet-89599',
    storageBucket: 'wallet-89599.appspot.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
